### ISSUE TITLE
yarn install/ npm install fails

### ISSUE THREAD

**Issue by partizanos** [vigetlabs/jest-with-nightmare#1]
Error trying to run

yarn install:
error https://registry.yarnpkg.com/fsevents/-/fsevents-1.0.14.tgz: unexpected end of file
error An unexpected error occurred: "https://registry.yarnpkg.com/react-scripts/-/react-scripts-0.6.1.tgz: unexpected end of file".

npm install: 
node-pre-gyp http GET https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.0.14/fse-v1.0.14-node-v51-darwin-x64.tar.gz
node-pre-gyp verb download using proxy url: "http://127.0.0.1:3129/"
node-pre-gyp ERR! Tried to download: https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.0.14/fse-v1.0.14-node-v51-darwin-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for fsevents@1.0.14 and node@7.7.2 (node-v51 ABI) (falling back to source compile with node-gyp)

**Comment by pjamgithub** [comment]
Could this be you are on node@7.7.2 rather than it's last stable verison, 6.11.2?

**Comment by nhunzaker** [comment]
Yikes. Sorry! I wasn't watching my own repo.

Checking this out now.

**Comment by nhunzaker** [comment]
I hit a few issues with the MD5 verification with Yarn. I've upgraded the dependencies and I can now install this correctly on the NodeJS 8.x release.
